# backend/tests/test_smoke.py
from fastapi.testclient import TestClient
from backend.main import app
import json

client = TestClient(app)

def create_test_akb(name: str, owner: str) -> str:
    response = client.post("/governance/akb", json={"name": name, "owner": owner})
    assert response.status_code == 200
    return response.json()["id"]

def test_root_endpoint():
    response = client.get("/")
    assert response.status_code == 200
    assert response.json() == {"message": "GARVIS Governance PoC Backend is running!"}

def test_docs_available():
    response = client.get("/docs")
    assert response.status_code == 200
    assert "openapi" in response.text

def test_akb_create_and_get():
    akb_id = create_test_akb("Test AKB", "test_owner")
    response_get = client.get(f"/governance/akb/{akb_id}")
    assert response_get.status_code == 200
    akb_data = response_get.json()
    assert akb_data["id"] == akb_id
    assert akb_data["name"] == "Test AKB"
    assert akb_data["owner"] == "test_owner"
    assert "entries" in akb_data

def test_evaluate_action():
    akb_id = create_test_akb("Eval AKB", "owner_eval")
    response_eval_read = client.post(f"/governance/akb/{akb_id}/evaluate", json={"akb_id": akb_id, "action": "read"})
    assert response_eval_read.status_code == 200
    assert response_eval_read.json()["allowed"] == True
    assert "Read action allowed" in response_eval_read.json()["detail"]
    response_eval_write = client.post(f"/governance/akb/{akb_id}/evaluate", json={"akb_id": akb_id, "action": "write"})
    assert response_eval_write.status_code == 200
    assert response_eval_write.json()["allowed"] == False

def test_generate_doc_requires_approval():
    akb_id = create_test_akb("DocGen AKB", "owner_docgen")
    response_gen_no_approve = client.post(f"/governance/akb/{akb_id}/generate-doc", json={"akb_id": akb_id, "approve": False})
    assert response_gen_no_approve.status_code == 200
    assert response_gen_no_approve.json()["ok"] == False
    assert "Approval required" in response_gen_no_approve.json()["content"]
    response_gen_approve = client.post(f"/governance/akb/{akb_id}/generate-doc", json={"akb_id": akb_id, "approve": True, "llm_adapter_key": "local_mock"})
    assert response_gen_approve.status_code == 200
    assert response_gen_approve.json()["ok"] == True
    assert "Document for DocGen AKB" in response_gen_approve.json()["content"]
    assert "Mock output from local LLM" in response_gen_approve.json()["content"]
    assert "Explainability: Generated by: local_mock" in response_gen_approve.json()["explainability"]

def test_audit_log_export():
    akb_id = create_test_akb("Audit AKB", "owner_audit")
    client.post(f"/governance/akb/{akb_id}/evaluate", json={"akb_id": akb_id, "action": "read"})
    client.post(f"/governance/akb/{akb_id}/generate-doc", json={"akb_id": akb_id, "approve": True, "llm_adapter_key": "local_mock"})
    response_json = client.get("/governance/audit/export?format=json")
    assert response_json.status_code == 200
    audit_data_json = response_json.json()
    assert audit_data_json["format"] == "json"
    assert isinstance(audit_data_json["data"], list)
    assert len(audit_data_json["data"]) >= 2
    response_csv = client.get("/governance/audit/export?format=csv")
    assert response_csv.status_code == 200
    assert response_csv.json()["format"] == "csv"
    assert "action,detail" in response_csv.json()["data"]

def test_llm_adapter_selection():
    akb_id = create_test_akb("Adapter Test AKB", "owner_adapter")
    resp_default = client.post(f"/governance/akb/{akb_id}/generate-doc", json={"akb_id": akb_id, "approve": True})
    assert "Mock output from local LLM" in resp_default.json()["content"]
    response_set = client.post("/governance/adapters/set_current", json={"adapter_key": "openai_like"})
    assert response_set.status_code == 200
    assert "openai_like" in response_set.json()["message"]
    resp_openai = client.post(f"/governance/akb/{akb_id}/generate-doc", json={"akb_id": akb_id, "approve": True, "llm_adapter_key": "openai_like"})
    assert resp_openai.status_code == 200
    assert "OpenAI-like output" in resp_openai.json()["content"]
